### ISSUE TITLE
There is an exception for adding two watcher

### ISSUE THREAD

**Issue by Hubery2757** [coreos/jetcd#125]
Exception info as below:

Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead@7f9132bb
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.coreos.jetcd.WatchImpl.getResumeWatchOptionWithWatcher(WatchImpl.java:299)
	at com.coreos.jetcd.WatchImpl.resumeWatchers(WatchImpl.java:252)
	at com.coreos.jetcd.WatchImpl.resume(WatchImpl.java:108)
	at com.coreos.jetcd.WatchImpl.access$400(WatchImpl.java:33)
	at com.coreos.jetcd.WatchImpl$1.onError(WatchImpl.java:140)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:499)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

You can reproduce ti as such steps:
1. Build a Client : ClientBuilder.newBuilder().endpoints() . 
2. Get watcher client:  watchClient = client.getWatchClient()
3. add two watchers  for  "/test1" and "/test2" as below:
    watcher = watchClient.watch(key, WatchOption.DEFAULT, new Watch.WatchCallback() {
            @Override
            public void onWatch(Header header, List<WatchEvent> list) {
                System.out.println("onWatch");
            }
            @Override
            public void onResuming() {
                System.out.println("onResuming");
            }
        }).get();
4.  Put value for "/test1", you can receive the PUT Watch event successfully.
5.  If you delete "/test1" or put value for "/test2", you can receive exception as above.

Could you locate and fix this issue as soon as possible ? Thanks a lot!

**Comment by fanminshi** [comment]
fixed by #126. closing.
