### ISSUE TITLE
Ip Resolve issue

### ISSUE THREAD

**Issue by smartminghan** [coreos/jetcd#207]
Hi, I use the same way as your test case to build and connect etcd  and below error happen.  It seems SmartNameResolver can't resolve the ip correctly. May i know how to fix it?

public static final String[] endpoints = System.getProperty(
      "etcd.endpoints",
      "http://localhost:2379,http://localhost:22379,http://localhost:32379").split(",");

Client client = ClientBuilder.newBuilder().setEndpoints(TestConstants.endpoints).build();

Error:
-------------------------
11:20:02.748 [grpc-default-executor-0] WARN com.coreos.jetcd.resolver.SmartNameResolver - Error wile getting list of servers
com.coreos.jetcd.exception.EtcdException: null
	at com.coreos.jetcd.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:9)
	at com.coreos.jetcd.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:13)
	at com.coreos.jetcd.resolver.SmartNameResolver.doResolve(SmartNameResolver.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unable to resolve endpoints [http://localhost:2379, http://localhost:22379, http://localhost:32379]
	... 4 common frames omitted

**Comment by lburgazzoli** [comment]
please use the latest sources, there were an issue that prevented the client to load the resolvers.

**Comment by fanminshi** [comment]
@smartminghan has the latest source solved the resolver issue?

**Comment by smartminghan** [comment]
sorry for late reply. yes. resolved. thanks.
