### ISSUE TITLE
spring boot did not support?

### ISSUE THREAD

**Issue by xingyunhui** [coreos/jetcd#229]
I use jetcd with spring boot  .But, when running the java program in my new project(build with maven), I am getting "java.lang.NoClassDefFoundError: io/netty/util/internal/DefaultPriorityQueue".
java version 1.8.0_121
spring boot version v1.5.2.RELEASE)
mvn dependency
         <dependency>
            <groupId>com.coreos</groupId>
            <artifactId>jetcd-core</artifactId>
            <version>0.0.1</version>
        </dependency>
shoud I downloaded other dependencies??
Error:
2017-08-26 22:32:14.849  WARN 61990 --- [ault-executor-0] io.grpc.internal.ChannelExecutor         : Runnable threw exception in ChannelExecutor

java.lang.NoClassDefFoundError: io/netty/util/internal/DefaultPriorityQueue
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.<init>(WeightedFairQueueByteDistributor.java:107) ~[netty-codec-http2-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.<init>(WeightedFairQueueByteDistributor.java:94) ~[netty-codec-http2-4.1.12.Final.jar:4.1.12.Final]
	at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:111) ~[grpc-netty-1.5.0.jar:1.5.0]
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:174) ~[grpc-netty-1.5.0.jar:1.5.0]
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:29) ~[grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:202) ~[grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:175) ~[grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.ManagedChannelImpl$SubchannelImplImpl.obtainActiveTransport(ManagedChannelImpl.java:813) ~[grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.GrpcUtil.getTransportFromPickResult(GrpcUtil.java:578) ~[grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.DelayedClientTransport.reprocess(DelayedClientTransport.java:280) ~[grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl$5.run(ManagedChannelImpl.java:719) ~[grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:72) ~[grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.runSerialized(ManagedChannelImpl.java:710) [grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:759) [grpc-core-1.5.0.jar:1.5.0]
	at com.coreos.jetcd.resolver.SmartNameResolver.doResolve(SmartNameResolver.java:141) [jetcd-core-0.0.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: io.netty.util.internal.DefaultPriorityQueue
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_121]
	... 18 common frames omitted

**Comment by ScienJus** [comment]
I think it is a netty version conflict between `netty-codec-http2` and `netty-common`.

Please report the result of `mvn dependency:list | grep 'netty-common'` or `mvn dependency:tree`.

**Comment by xingyunhui** [comment]
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.0.45.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.7.Final:compile

**Comment by ScienJus** [comment]
@xingyunhui 

`DefaultPriorityQueue` is not exists in `netty-common:4.1.7.Final`, you should upgrade to at 
least `4.1.9.Final`.

More details:

https://github.com/netty/netty/commit/3482651e0c29edfa02f189751c704ebe4fe8f54c

**Comment by xiang90** [comment]
@xingyunhui try what @ScienJus suggested. i believe it would solve your issue. so, closing.
