### ISSUE TITLE
Issue with SSL

### ISSUE THREAD

**Issue by Abhijith1** [coreos/jetcd#275]
I'm unable to create an etcd client as specified here: https://github.com/coreos/jetcd/commit/1906f202189392a212c2c947e293d25eea5165d5
I'm creating the client something like this: 
`Client client = Client.builder()
          .endpoints(endpoints)
          .authority(authority)
          .sslContext(GrpcSslContexts.forClient()
              .trustManager(is)
              .build())
          .build();` 
I'm unable to add the `.authority()` part as it doesn't exist in the `ClientBuilder.java` file.

I added the jetcd dependancy in my gradle dependencies like this:
`compile 'com.coreos:jetcd-core:0.0.1'`

Any help?

**Comment by lburgazzoli** [comment]
You need to build jetcd from sources

**Comment by Abhijith1** [comment]
@lburgazzoli I did that and for some reason the `jetcd-core-0.1.0-SNAPSHOT.jar` jar generated was causing an issue with `io.grpc.netty.GrpcSslContexts;` library.
So I tried importing the `jetcdctl.jar` (The jetcdctl example) jar and I'm able to get the authority function now and the .
Now the connect to etcd works fine but when I try ro get a key, I get this error:
`com.coreos.jetcd.exception.EtcdException: Channel closed while performing protocol negotiation`

I'm building the etcd Client like this:
      client = Client.builder()   //Create etcd client with certificate
                       .endpoints(<etcdAddr>)
                        .user(ByteSequence.fromString(<username>))
                    .password(ByteSequence.fromString(<password>))
                    .authority("etcd-ssl")
                    .sslContext(GrpcSslContexts.forClient()
                            .trustManager(new File("<My certificate file location>", "ca.pem")
                            .build())
                        .build();

**Comment by lburgazzoli** [comment]
What is the issue with jetcd-core-0.1.0-SNAPSHOT.jar ?
Did you install the right openssl libraries ?

**Comment by Abhijith1** [comment]
I just added these dependencies and I don't encounter the issues that I was facing earlier:
   ```
    compile group: 'io.grpc', name: 'grpc-core', version: '1.9.0'
    compile group: 'io.grpc', name: 'grpc-netty', version: '1.9.0'
    compile group: 'io.grpc', name: 'grpc-protobuf', version: '1.9.0'
    compile group: 'io.grpc', name: 'grpc-stub', version: '1.9.0'
    compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.20'
```

It was probably not working earlier because I was using the older versions as mentioned here:
https://github.com/coreos/jetcd#manual

But I still get this error:
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at bms.config.Config.init(Config.java:83)
	at Main.main(Main.java:6)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.coreos.jetcd.internal.impl.Util.lambda$toCompletableFutureWithRetry$1(Util.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at com.coreos.jetcd.internal.impl.ClientConnectionManager$AuthTokenInterceptor$1$1.onClose(ClientConnectionManager.java:280)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 3 more`

**Comment by Abhijith1** [comment]
@lburgazzoli Any update on this? I'm kind of stuck because of this. :(

**Comment by lburgazzoli** [comment]
I do not know how you have set-up your project so it is quite hard to understand what it is happening so I recommend:

1. use maven to handle dependencies
2. look at ssl test to see what we do

**Comment by Abhijith1** [comment]
@lburgazzoli I was incorrectly passing the hostname to the authority() method. I now have the library working with SSL.
However, as discussed on other threads, I too have the problem of passing hosts to authority when dealing with multiple etcd hosts.

**Comment by nsirohi-ps** [comment]
@Abhijith1 , what did you have to pass to the authority method to get this to work?
