### ISSUE TITLE
Deadlock in LeaseImpl between  closeLock and ownerLock

### ISSUE THREAD

**Issue by koaal** [coreos/jetcd#315]
effected jetcd version: all

"grpc-default-executor-4" daemon prio=10 tid=0x00007fcf0c018000 nid=0x5c8c waiting for monitor entry [0x00007fceb46d7000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.coreos.jetcd.internal.impl.LeaseImpl$KeepAliveListenerImpl.isClosed(LeaseImpl.java:456)
        - waiting to lock <0x00000007360d0120> (a java.lang.Object)
        at com.coreos.jetcd.internal.impl.LeaseImpl$KeepAliveListenerImpl.enqueue(LeaseImpl.java:409)
        at com.coreos.jetcd.internal.impl.LeaseImpl$KeepAlive.sentKeepAliveResp(LeaseImpl.java:519)
        at com.coreos.jetcd.internal.impl.LeaseImpl.processKeepAliveResponse(LeaseImpl.java:302)
        - locked <0x000000073cbdfb48> (a com.coreos.jetcd.internal.impl.LeaseImpl)
        at com.coreos.jetcd.internal.impl.LeaseImpl.access$300(LeaseImpl.java:49)
        at com.coreos.jetcd.internal.impl.LeaseImpl$6.onNext(LeaseImpl.java:248)
        at com.coreos.jetcd.internal.impl.LeaseImpl$6.onNext(LeaseImpl.java:245)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:406)
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:36)
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:36)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:530)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)

"pool-21-thread-1" prio=10 tid=0x00007fcf41899800 nid=0x2adc waiting for monitor entry [0x00007fcf74123000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.coreos.jetcd.internal.impl.LeaseImpl$KeepAlive.removeListener(LeaseImpl.java:526)
        - waiting to lock <0x000000073cbdfb48> (a com.coreos.jetcd.internal.impl.LeaseImpl)
        at com.coreos.jetcd.internal.impl.LeaseImpl$KeepAliveListenerImpl.close(LeaseImpl.java:465)
        - locked <0x00000007360d0120> (a java.lang.Object)
        at com.coreos.jetcd.internal.impl.LeaseImpl$KeepAlive.close(LeaseImpl.java:534)
        at com.coreos.jetcd.internal.impl.LeaseImpl$8$1.apply(LeaseImpl.java:319)
        at com.coreos.jetcd.internal.impl.LeaseImpl$8$1.apply(LeaseImpl.java:314)
        at com.google.common.collect.Iterators.removeIf(Iterators.java:242)
        at com.coreos.jetcd.internal.impl.LeaseImpl$8.run(LeaseImpl.java:314)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)

**Comment by lburgazzoli** [comment]
@koaal can you provide a reproducer ?

**Comment by koaal** [comment]
It is hard to reproduce in functional test instead of performance test, my functional logic is as below:

`
//step1: create a lease
long leaseId = createLease(nodeId, appName, profile, leaseTtl);

//step2: keepalive the lease
kal = etcdClient.getLeaseClient().keepAlive(leaseId);

//step3: create a node on etcd with lease
createLeaseNode(nodeId, appName, profile, leaseId,leaseTtl);

//listening the node created above, if delete event is received, reproduce step 1, 2 and 3
nodeListenFuture = listenNodeDelete(nodeId, appName, profile,leaseTtl,leaseId);

`

**Comment by koaal** [comment]
check from the code, the problem is quite  obvious:

//keepalive listener hold the closeLock and then try to remove itself from keepalive
    @Override
    public void close() {
      synchronized (this.closedLock) {
        this.closed = true;
        this.owner.removeListener(this);
        this.service.shutdownNow();
      }
    }

//another lock (object lock of LeaseImpl) is required when keepalive try to remove its listener
    public void removeListener(KeepAliveListenerImpl l) {
      this.listenersSet.remove(l);
      synchronized (this.ownerLock) {
        if (this.listenersSet.isEmpty()) {
          this.owner.remove(this.leaseId);
        }
      }
    }

**Comment by lburgazzoli** [comment]
oh yeah, would you mind to send a pr?

**Comment by koaal** [comment]
i would like to do it.

**Comment by lburgazzoli** [comment]
@koaal closing this as I've merged your PR

**Comment by LaughXP** [comment]
Is this bug solved?

**Comment by lburgazzoli** [comment]
it should be
