### ISSUE TITLE
Unable to resolve endpoints

### ISSUE THREAD

**Issue by zhaorendong** [coreos/jetcd#320]
I created etcd-v3 cluster in kubernetes-1.9.1,and I get keys from etcd by jetcd-core. When I used url that like "http://192.168.18.4:2379", I can get keys . But when I used url that like "http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy",I can't get anything,and it EtcdException.The "http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy" is kubernetes master proxy url.My java code is following:

Client client = Client.builder().endpoints("http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy").build();
//			Client client = Client.builder().endpoints("http://192.168.18.4:2379").build();
List<com.coreos.jetcd.data.KeyValue> kvs = client.getKVClient().get(ByteSequence.fromString("/calico")).get().getKvs();
			for(com.coreos.jetcd.data.KeyValue kv :kvs){
				System.out.println("==================>>>>>"+kv.getKey().toStringUtf8());
			}

EtcdException:
com.coreos.jetcd.common.exception.EtcdException: Unable to resolve endpoints [http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy]
	at com.coreos.jetcd.common.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:30)
	at com.coreos.jetcd.resolver.SmartNameResolver.doResolve(SmartNameResolver.java:139)
	at com.coreos.jetcd.resolver.SmartNameResolver$$Lambda$415/83112112.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
15:18:37.260 ku8eye [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [io.grpc.internal.ManagedChannelImpl-1] Failed to resolve name. status=Status{code=NOT_FOUND, description=null, cause=null}
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: NOT_FOUND
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887)
	at org.ku8eye.service.NetWorkService.getSvc(NetWorkService.java:540)
	at org.ku8eye.service.NetWorkService$$FastClassBySpringCGLIB$$1a66ba61.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.ku8eye.service.NetWorkService$$EnhancerBySpringCGLIB$$74c2ef62.getSvc(<generated>)
	at org.ku8eye.ctrl.NetworkController.getSvc(NetworkController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: NOT_FOUND
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.coreos.jetcd.internal.impl.Util.lambda$toCompletableFutureWithRetry$1(Util.java:125)
	at com.coreos.jetcd.internal.impl.Util$$Lambda$420/1333810191.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at com.coreos.jetcd.internal.impl.ClientConnectionManager$AuthTokenInterceptor$1$1.onClose(ClientConnectionManager.java:280)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 3 more

**Comment by lburgazzoli** [comment]
This URI style `http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy` is not supported, can you provide some more info so I can see if I can support it ?

**Comment by zhaorendong** [comment]
http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy
http://192.168.18.3:8080 : the kubernetes master url
namespaces/kube-system : the kube-system is one of kubernetes namespace
services/calico-etcd1:2379 : the calico-etcd1 is etcd service name and 2379 is service port
/api/v1/: is hard code
/proxy :is hard code

**Comment by lburgazzoli** [comment]
Are you using it inside kubernetes ?

**Comment by zhaorendong** [comment]
I deployed etcd cluster in many kubernetes cluster,then I want get something from etcd every kubernetes cluster by kubernetes master proxy. I used it inside one of the kubernetes cluster.

**Comment by lburgazzoli** [comment]
if you are inside kubernetes you can simple use the service name or dns src record(https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/), if you want to access other clusters you may need to use kubernetes federation.

**Comment by lburgazzoli** [comment]
As alternative you need to implement a URIResolver which is able to query kubernetes services and grab the address to connecto to.

**Comment by zhaorendong** [comment]
Now, I saved all kubernetes services and grab the address in my database, so I can access other clusters by the cluster master proxy. I have also used this way to visit other services before, There was no problem in doing this, but when I use jetcd-core,it reported errors. When I used "http://192.168.18.4:2379" that OK，but used ""http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy" it error.

**Comment by lburgazzoli** [comment]
Again, we need to resolve http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy to host/port, how would you do so ?

**Comment by zhaorendong** [comment]
I can't access etcd cluster with etcdctl(v3) by the way, I accessed etcd cluster with rest api .

[root@192 ~]#      curl http://192.168.18.3:8080/api/v1/namespaces/kube-system/services/calico-etcd1:2379/proxy/v2/keys
{"action":"get","node":{"dir":true,"nodes":[{"key":"/hello","value":"world","modifiedIndex":6,"createdIndex":6}]}}

**Comment by lburgazzoli** [comment]
jetcd uses grpc (v3) so you won't be able to access rest endpoints
