### ISSUE TITLE
Test failures on initial build

### ISSUE THREAD

**Issue by at88mph** [coreos/jetcd#56]
Hello,

I'm prototyping ```etcd``` to run our local service discovery.

I'm running Debian 8.0, and using the official [Quay Docker image](http://quay.io/coreos/etcd) to run ```etcd```.

I've started the docker single instance cluster using:
```
docker run -d -v /usr/share/ca-certificates/:/etc/ssl/certs -p 4001:4001 -p 2380:2380 -p 2379:2379 \
 --name etcd quay.io/coreos/etcd etcd \
 -name etcd0 \
 -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001 \
 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
 -initial-advertise-peer-urls http://${HostIP}:2380 \
 -listen-peer-urls http://0.0.0.0:2380 \
 -initial-cluster-token etcd-cluster-1 \
 -initial-cluster etcd0=http://${HostIP}:2380 \
 -initial-cluster-state new
```

If I clone the latest ```coreos/jetcd``` and run ```mvn package```, I get a test failure:
```
Tests run: 34, Failures: 2, Errors: 0, Skipped: 3, Time elapsed: 28.542 sec <<< FAILURE! - in TestSuite
testListCluster(com.coreos.jetcd.EtcdClusterClientTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: Members: 1 expected [3] but found [1]
	at com.coreos.jetcd.EtcdClusterClientTest.testListCluster(EtcdClusterClientTest.java:33)
```

Is this a known issue?

Also, if I try to run it again, I get that same error, plus a new one:
```
testGetSortedPrefix(com.coreos.jetcd.EtcdKVTest)  Time elapsed: 0.034 sec  <<< FAILURE!
java.lang.AssertionError: expected [3] but found [4]
	at com.coreos.jetcd.EtcdKVTest.testGetSortedPrefix(EtcdKVTest.java:115)
```

So as a secondary issue, there may be a need to setup the environment properly.

Thank you,
Dustin

**Comment by xiang90** [comment]
This code is not production ready. Can you try to help to fix the issue you found?

**Comment by at88mph** [comment]
Yes.  I'll aim for a pull request as soon as I can.

**Comment by at88mph** [comment]
The test just expects a 3-node cluster to be running, which I don't have.  I will try to force it to accommodate however many nodes there are actually running, which is 1 in my case.

Also, is there a known issue when adding a member to a single instance cluster?

When the ```testAddMember``` of the ```EtcdClusterClientTest``` method successfully adds a member, the service seems to get into an endless loop:
```
2016-11-03 21:22:53.967579 I | rafthttp: started peer d957e4de47a0dc79
2016-11-03 21:22:53.967623 I | rafthttp: added peer d957e4de47a0dc79
2016-11-03 21:22:53.969832 I | rafthttp: started streaming with peer d957e4de47a0dc79 (stream MsgApp v2 reader)
2016-11-03 21:22:53.970070 I | rafthttp: started streaming with peer d957e4de47a0dc79 (stream Message reader)
2016-11-03 21:22:54.706712 W | raft: 38f97fa9300bde7e stepped down to follower since quorum is not active
2016-11-03 21:22:54.706758 I | raft: 38f97fa9300bde7e became follower at term 2
2016-11-03 21:22:54.706772 I | raft: raft.node: 38f97fa9300bde7e lost leader 38f97fa9300bde7e at term 2
2016-11-03 21:22:55.806711 I | raft: 38f97fa9300bde7e is starting a new election at term 2
2016-11-03 21:22:55.806757 I | raft: 38f97fa9300bde7e became candidate at term 3
2016-11-03 21:22:55.806773 I | raft: 38f97fa9300bde7e received vote from 38f97fa9300bde7e at term 3
2016-11-03 21:22:55.806789 I | raft: 38f97fa9300bde7e [logterm: 2, index: 89] sent vote request to d957e4de47a0dc79 at term 3
2016-11-03 21:22:57.306690 I | raft: 38f97fa9300bde7e is starting a new election at term 3
2016-11-03 21:22:57.306746 I | raft: 38f97fa9300bde7e became candidate at term 4
```
Is it a result of a single instance cluster?  Does this need to be debugged?

**Comment by StupidHod** [comment]
Hello,
@at88mph After you use testAddMember, there are 2 members in the term. For raft with 2 members, the cluster get a leader only after  2 members all vote to the candidate. You do not have another member, so the cluster get into a endless loop without a leader.
You can use the [https://github.com/coreos/jetcd/blob/master/scripts/run_etcd.sh](url) to start a 3 nodes cluster for the test.
The test is designed to run in the enviroment with 3 nodes that initized with run_etcd.sh.

**Comment by at88mph** [comment]
Hi @StupidHod ,
I got carried away with the test setup being automated and was trying to resolve it.  Thank you for the reply.

**Comment by akauppi** [comment]
@StupidHod Thanks for mentioning

> The test is designed to run in the enviroment with 3 nodes that initized with run_etcd.sh.

I believe that would be beneficial to be on the front `README`. Will check, and probably make a PR to get a faster ignition experience for newcomers.

**Comment by fanminshi** [comment]
`README` is updated via https://github.com/coreos/jetcd/pull/72. closing. Thanks @akauppi !
