### ISSUE TITLE
Watch does not work well

### ISSUE THREAD

**Issue by riclava** [coreos/jetcd#93]
When I using code below to start watch a key, but failed with an exception
```
WatchOption watchOption = WatchOption.DEFAULT;
try {
	watcher = watchClient.watch(key, watchOption, new WatchCallback() {
		@Override
		public void onWatch(EtcdHeader header, List<WatchEvent> events) {
			System.out.println("onWatch() called");
		}

		@Override
		public void onResuming() {
		}
	}).get();
} catch (InterruptedException | ExecutionException e) {
	logger.error("Error watch leader", e);
} catch (Exception e) {
	logger.error("Unexpected exception", e);
}
```
Exception:
```
May 10, 2017 10:14:38 AM io.grpc.internal.SerializingExecutor$TaskRunner run
SEVERE: Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead@6d32cbca
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.coreos.jetcd.EtcdWatchImpl.getResumeWatchOptionWithWatcher(EtcdWatchImpl.java:298)
	at com.coreos.jetcd.EtcdWatchImpl.resumeWatchers(EtcdWatchImpl.java:251)
	at com.coreos.jetcd.EtcdWatchImpl.resume(EtcdWatchImpl.java:107)
	at com.coreos.jetcd.EtcdWatchImpl.access$400(EtcdWatchImpl.java:32)
	at com.coreos.jetcd.EtcdWatchImpl$1.onError(EtcdWatchImpl.java:139)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:499)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
the root cause is:
```
  private WatchOption getResumeWatchOptionWithWatcher(Watcher watcher) {
    WatchOption oldOption = watcher.getWatchOption();
    return WatchOption.newBuilder().withNoDelete(oldOption.isNoDelete())
        .withNoPut(oldOption.isNoPut())
        .withPrevKV(oldOption.isPrevKV())
        .withProgressNotify(oldOption.isProgressNotify())
        .withRange(oldOption.getEndKey().get())                  // THIS LINE
        .withRevision(watcher.getLastRevision() + 1)
        .withResuming(true)
        .build();
  }
```
wish u to give a solution, thanks

**Comment by fanminshi** [comment]
@riclava I am reviewing the watch implementation at the moment. I will let know you when this issue get fixed.

**Comment by riclava** [comment]
Thanks !
Besides, I use etcd v3.1.5 server in cluster mode with 3 nodes.

**Comment by fanminshi** [comment]
@riclava I am submitting an pr to change watch interface https://github.com/coreos/jetcd/pull/98. that change might broke your code. However, I think the new interface might be easier to use.  Take a look at the new interface and let me know what you think.

**Comment by fanminshi** [comment]
fixed via https://github.com/coreos/jetcd/pull/126.
